version: '3.8'

services:
  webserver:
    platform: linux/arm64
    container_name: oppia-webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    volumes:
      - .:/app/oppia
      - /app/oppia/node_modules
    environment:
      - NODE_ENV=development
    # depends_on:
      # - google_cloud_sdk

  google_cloud_sdk:
    platform: linux/arm64
    image: google/cloud-sdk:364.0.0
    ports:
      - "8089:8089"
      # - "8181:8181"
      - "8000:8000"
    volumes:
      - /app/cloud_datastore_emulator_cache
    command: dev_appserver.py app_dev.yaml --host=localhost --port=8181