version: '3.8'

services:
  webserver:
    platform: linux/arm64
    container_name: oppia-webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    volumes:
      - .:/app/oppia
      - node_modules:/app/oppia/node_modules
    environment:
      - NODE_ENV=development
    # depends_on:
      # - google_cloud_sdk
    command: ./node_modules/.bin/ng build --watch
  
  webpack-compiler:
    platform: linux/arm64
    container_name: oppia-webpack-compiler
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/oppia
      - node_modules:/app/oppia/node_modules
    command: node ./node_modules/webpack/bin/webpack.js --config ./webpack.dev.config.ts --watch

  google_app_engine:
    build: 
      context: .
      dockerfile: Dockerfile.google_cloud_sdk
    container_name: oppia-app-engine
    ports:
      # - "8089:8089"
      # - "8181:8181"
      - "8000:8000"
    volumes:
      - .:/app/oppia
    # environment:
    #   - CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK=false
    depends_on:
      - webserver
      - webpack-compiler
    # restart: unless-stopped
    # command: ../google-cloud-sdk/bin/dev_appserver.py /app/oppia/app_dev.yaml --host=localhost
    # command: dev_appserver.py ../app/oppia/app_dev.yaml --host=localhost
    command: ../google-cloud-sdk/bin/dev_appserver.py /app/oppia/app_dev.yaml --runtime custom --host=localhost
    # command: ls ../google-cloud-sdk/
  
  google_cloud_datastore:
    build:
      context: .
      dockerfile: Dockerfile.google_cloud_sdk
    container_name: oppia-cloud-datastore
    ports:
      - "8089:8089"
    volumes:
      - .:/app/oppia
    depends_on:
      - google_app_engine
    command: ../google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator start --host=localhost --port=8089 --store_on_disk=False  --consistency=1.0 /app/cloud_datastore_emulator_cache

  firebase_emulator:
    image: node:16.13.0-alpine
    container_name: oppia-firebase-emulator
    ports:
      - "9099:9099"
    volumes:
      - .:/app/oppia
      - node_modules:/app/oppia/node_modules
    command: /app/oppia/node_modules/firebase-tools/lib/bin/firebase.js emulators:start --only auth --project dev-project-id --config /app/oppia/.firebase.json --export-on-exit /app/firebase_emulator_cache


volumes:
  node_modules: