name: Docker Setup Test
on: [push]
  # merge_group:
  #   types: [checks_requested]
  # push:
  #   branches:
  #     - develop
  #     - release-*
  # pull_request:
  #   branches:
  #     - develop
  #     - release-*

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout to the Oppia repository code
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - uses: ./.github/actions/merge

      - name: Check if cache exists
        id: cache-check
        run: echo ::set-output name=cache-exists::$(docker images -q oppia-angular-build)

      - name: Cache Docker images
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-compose-${{ hashFiles('docker-compose.yml') }}
          restore-keys: |
            ${{ runner.os }}-docker-compose-

      - name: Build Docker Compose
        run: |
          # If cache exists, use it, otherwise build Docker Compose
          if [ -n "${{ steps.cache-check.outputs.cache-exists }}" ]; then
            echo "Docker images found in cache. Skipping build..."
          else
            echo "Docker images not found in cache. Building..."
            docker compose build
          fi

      # - name: Build Images
      #   run: |
      #     echo ---Building Docker Images---
      #     docker compose build
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: false
      #     load: true
      #     tags: shivkant/oppia:1.0.0
      #     file: ./docker/Dockerfile
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          
      - name: Start Containers
        run: |
          echo ---Starting Containers---
          docker compose up -d

      - name: Checking server reachability
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:8181/; then
              echo ---Dev-server is up---
              exit 0
            else
              echo ---Retrying in 30 seconds---
              sleep 30
            fi
          done
          echo ---Dev-server is not started after all retries---
          exit 1
          
      - name: Stop Containers
        run: docker compose down
